name: Zomato Follow Bot

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the script on a schedule
  schedule:
    # Runs at 04:00 UTC every day. This is 9:30 AM IST.
    # Use https://crontab.guru/ to customize the schedule.
    - cron: '0 4 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium

      - name: 4. Run the Zomato Follow script
        env:
          # This makes the GitHub Secret available as an environment variable in the script
          ZOMATO_COOKIES: ${{ secrets.ZOMATO_COOKIES }}
        run: python main.py
      
      - name: 5. Upload results artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: follow-results
          path: follow_results.csv # The path to the file generated by the script
